---
title: "`ggplot2` Shortcuts"
author: "Jonathan Carroll"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{`ggplot2` Shortcuts}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

This package allows easy access to some common `ggplot2` tasks. For example, rotating the `x` axis labels is a very frequently looked up task, and we can make it easier. If we create a simple `ggplot2` plot

```{r, message = FALSE}
library(ggplot2)
library(cowplot)
library(ggeasy)

p <- ggplot(mtcars, aes(hp, mpg)) + geom_point()
```

then by default, this looks like

```{r, fig.width = 6, fig.height = 6}
p + labs(title = "ggplot2 default")
```

We can perform various rotations though

```{r, fig.width = 8, fig.height = 8}
p1 <- p + 
    easy_rotate_x_labels() + 
    labs(title = "default rotation")
p2 <- p + 
    easy_rotate_x_labels(angle = 45, side = "right") + 
    labs(title = "angle = 45")
p3 <- p + 
    easy_rotate_x_labels("startattop") + 
    labs(title = "text starts at top")
p4 <- p + 
    easy_rotate_x_labels("startatbottom") + 
    labs(title = "text starts at bottom")
    
plot_grid(p1, p2, p3, p4, nrow = 2)
```

